project:
  type: default

crossref:
  ref-hyperlink: true

format:
  html:
    toc: true
    toc-depth: 3
    number-sections: true
  pdf:
    toc: true
    number-sections: true
    include-in-header: header.tex
