name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install npm dependencies
        run: npm ci

      - name: Build C++ via Make
        run: make

      - name: Run npm tests
        run: npm test

  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v6
        with: { python-version: '3.11' }
      - run: pip install -U pip pytest ruff black pandas
      - run: ruff check .
      - run: black --check .
      - run: pytest -q
      - name: Check markdown files
        uses: actions/checkout@v4
        with:
          repository: actions/markdown-link-checker

